apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ib
spec:
  provider: azure
  parameters:
    useIdentityBinding: "true"
    userAssignedIdentityID: 6995fd4d-e405-431a-a34b-ffe4b13b131d # Update to your user assigned identity ID
    keyvaultName: jialuncai20251120 # Update to your keyvault name
    tenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47
    objects: |
      array:
      - |
        objectName: my-secret
        objectType: secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ib-read-secret
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ib-read-secret
rules:
  - verbs: ["use-managed-identity"]
    apiGroups: ["cid.wi.aks.azure.com"]
    resources: ["6995fd4d-e405-431a-a34b-ffe4b13b131d"] # Update to your user assigned identity ID
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ib-read-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ib-read-secret
subjects:
  - kind: ServiceAccount
    name: ib-read-secret
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: ib-read-secret
spec:
  serviceAccount: ib-read-secret
  containers:
    - name: read-secret
      image: mcr.microsoft.com/azure-cli:cbl-mariner2.0
      command: ["bash", "-c", "sleep infinity"]
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "ib"
